language: python
matrix:
  include:
  - name: R 3.5.1
    env: R_VERSION=3.5.1
before_install:
  - pip install awscli
script: "./build.sh $R_VERSION"
env:
  global:
  - secure: 1Wevv4NOFHuGXQdGRBIpnnRGUqKarAudG48oJS+HAZSBbqyHkkEQdR+pzH/qbGkhaJmBaEJoUrTodltB5bAFRf5zvJnhdTI32TdENRzp6JP2EiDhXg7SPNtwpQzemEUvFFoHrq/x5BK1jR/bkv+VrMthZR8BDR3EfLBwMWe8PdmuHvVrXYn9JkibJoa3+9kJTW1PHd74tYEmOEV9bmakLZAUH/zkoRtGt+tv4NiQ9e3YcuR+KLGeZJrQju2DkW3SLT99u9bxu8UIcsvylo9BgcGf/82+dj7pNfD4fZNBE26uoqNcOsQGhIQ/bw4cUH7pTPYdAoFteBjTxPnUo6tT7n9X9rA3D1at9gVYmjlXvKwHNY5T9oMTyUzpJCh/tZ7Rexm2FHT6P+83HRWBJXw5MvKVqgeCuu3Dgyg0e5Dvv9TV8gfi2geoWDwA1zKvcZC2+EAz3AIhfVNK7ueGeQ6f+qp/Iq7LCI9T7xhrJ+iFy6vP7oWkWSuJ2s0veUQQDMjYdEBhO+P3K2vpzCvAfX1c7SOFsZzYWNEaBzFVN3L1pPRZZJjY/5P5LudEZNm0NGeiloLL3NpaY0568y/lDb619/Ch6XL0kf54sJ0av1NKnAi91MHjNm0ZvBKK5QhnX7i8U2at7319MrYWv2W/9xVbPz9arb3lfu9L/lRQzsvOucs=
  - secure: MPQXc1QJnx6OmVDXLgPm9MHWQkPfyP3Nl+ddMcPFe53QqzNunXaSK+R2RSPpofzvEmPW23inf5xjMP2IVUSWPerZz9Vlin7EO4xNNtGwv7scRUXgvrTIES67KL8ME69gOcNOegu+WiOdkkYULqtX25EEMWTX73mYrXQAfqvuvXzjYMB/5EgJgchx8Wvt6as63/d3Zc6VEwf34XvMX3kyDDAetU13vrTQ9VnaVwTmchcABG3WdKNjt0T3UkKVeEul7LeVS6gZ4V5I/Ef5eydtUTWanIJSK9ctLEuNIq/OM6SBtJmAbHKd4CRdtMAM8dt6Bmlc3PSE+URd7rIDhE0OAobYBOit/rEZoq/DF7n5hs+xMaarkWOaE6u1iUBlyTMKF2cqnJtr+Z11dkmH4Y+Vq2ccjf+4OOnpjgRwpcEEqPRqfQx1EYiFg/d4rywhlHmCxGHXCBKRQrZqjpBWbEvdEKIm+roEK4oYj4aHBiF+xfaxGsYVMXC1KEKR/JSBPXKpAhe5BNKOamxtgtssczRu10jniwiPQU3Zy0IjZ8WZ1YXSzrRksmKdiH8JrZ0v/9l6CxGhhX5OA3n66w9UTmC3DKcE9/XN4y2FQAmsvpZ00ST+hYV4JbTXlvx5BCzH1/b9zzl+oH3MobRN8TMRkD2imTB/BXIS75s2+drWmiIUUYY=
